### ISSUE TITLE
[BUG] Dates (start, end) do not get stored/saved on initial creation.

### ISSUE THREAD

**Issue by wunschadresse** [Leantime/leantime#2152] opened 2023-12-17 04:18 UTC
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [x] Cloud Hosted Version
* [ ] Self Hosted

**Describe the bug**
When creating a new task, entered start and end date are not saved/written to the task.

**To Reproduce**
1. Click on +New task from anywhere on the platform
2. Enter a title, due, start and end date
3. Hit save or save and close
4. Check the task again for the dates

**Expected behavior**
All dates should be saved.

**Additional context**
The due date is saved correctly.

**Comment by pablopoo** [comment] 2023-12-20 13:08
Also experienced this on 2.4.8. Previous task created on old versions get the time part lost when modified.

**Comment by marcelfolaron** [comment] 2023-12-22 21:26
I was not able to reproduce this. Is this on 2.4.8? Is this only a specific task screen?

**Comment by marcelfolaron** [comment] 2023-12-22 21:31
Nvm found it: https://github.com/Leantime/leantime/pull/2161

**Comment by marcelfolaron** [comment] 2024-01-17 00:03
Fixed in 3.0.0

**Closed by marcelfolaron** 2024-01-17 00:03 UTC
