### ISSUE TITLE
[BUG] Incorrect password after second attempt to log in.

### ISSUE THREAD

**Issue by distresscode** [Leantime/leantime#1781] opened 2023-07-30 14:21 UTC
**What set up are you using**
Self Hosted via Cloudron https://www.cloudron.io/store/io.leantime.cloudronapp.html

**Describe the bug**
incorrect login credentials on fresh installs – seems to happen only once and can be remedied by resetting the password. I can reproduce this on multiple fresh installs of Leantime. Resetting the password via the FORGOT PASSWORD link does the trick and seems to permanently fix the issue. 

**To Reproduce**
Fresh install of Leantime on a Cloudron server. Logging in via default credentials, then changing those values to something secure. Log in again with those credentials and it will work the first time. On the second login, it will say WRONG EMAIL/PASS. Resetting the password via the FORGOT PASSWORD link does the trick and seems to permanently fix the issue. 

**Expected behavior**
It should log in without having to reset password.

**Leantime Version**
Leantime v2.3.27

**Server**
Cloudron 7.5.0 on Ubuntu 22.04

**Notes**
This might be related/caused by Redis. Please see issue #1780 for more information.

**Comment by jaykayenn** [comment] 2023-08-10 20:50
Same on Docker. Cannot login after first run. 
Attempted password recovery results in server timeout. (SMTP config error maybe? But then the server dies silently.)

**Comment by jdel** [comment] 2023-08-18 15:43
Saw this issue as well. It seems to be related to the users notification settings.

It is easy to reproduce and verify with the latest docker container. 

  1. In the database, select the user (admin for example) and copy the password hash for a reference. 

  2. In leantime, connected as the admin user, go and change any notification setting.

  3. In the database, select the same user and observe that the password hash had changed.

**Comment by marcelfolaron** [comment] 2023-08-23 12:04
The notification issue is fixed in our master branch. Re the first login, I wasn't able to reproduce that. I have not set up cloudron, how do they set up the initial user account? Is it through our installation script or do they have their own set up?

**Comment by marcelfolaron** [comment] 2023-08-26 16:50
This should now be fixed in 2.4-beta

**Closed by marcelfolaron** 2023-08-26 16:50 UTC
Labels: bug
