### ISSUE TITLE
[BUG] Cant delete a milestone which isnt assigned

### ISSUE THREAD

**Issue by isi2010** [Leantime/leantime#2432] opened 2024-03-23 12:11 UTC
**What set up are you using**
[X ] Self Hosted

**Describe the bug**
I cant delete milestones which arent assigned. ,

**To Reproduce**
1. Go to ToDo
2. Click on Add todo
3. Scroll down to milestone and add a milestone
4. Remove the milestone from the todo
5. then go on milestones
6. cant delete the milestone

**Expected behavior**
I should be able to delete milestones as i want as long as they arent assigned to a task. 

**Leantime Version**
3.0.5

**Server**
Apache, nginx

**PHP / MySQL Version**
8.1.27

**Comment by marcelfolaron** [comment] 2024-04-28 18:00
Is that still an issue. I can't reproduce this in 3.1.2

**Comment by isi2010** [comment] 2024-04-28 18:19
I’m not sure cause we switched to Jira in the meanwhile

**Comment by marcelfolaron** [comment] 2024-04-30 02:12
Ah, sorry to hear. Will close this for now.

**Closed by marcelfolaron** 2024-04-30 02:12 UTC
