### ISSUE TITLE
[BUG] 404 on PATCH 

### ISSUE THREAD

**Issue by poetaster** [Leantime/leantime#2134] opened 2023-12-08 14:35 UTC
**What set up are you using**
* [ ] Cloud Hosted Version
* [x ] Self Hosted

**Describe the bug**
Operations like xhr patch are failing on the route: /hx
For instance:

```XHRPATCH https://lean.veritably.ai/hx/projects/checklist/update-subtask/ [HTTP/2 404  62ms]```

When trying to update 'Define Scope' prereqs. checkboxes.

**To Reproduce**
1. Go to Project Dashboard
2. Click on 'Define Scope'
3. Check checkbox for 'Describe your project'
4. See error 404

**Expected behavior**
Patch should apply

**Leantime Version**
2.4.7

**Server**
Apache behind ha-proxy

**PHP / MySQL Version**
PHP 8.2.7
Maria 10.5

**Additional context**

The apache config has:

```	
DocumentRoot /var/www/leantime/public
``` 

Which might explain it.  But, that's what is implied it should be in the install docs.

**Comment by marcelfolaron** [comment] 2024-01-04 21:03
Duplicate of: #2146

**Closed by marcelfolaron** 2024-01-04 21:03 UTC
Labels: duplicate
