### ISSUE TITLE
[BUG] Tasks which with status "done" are still shown in the calendar as "Due To-Do"

### ISSUE THREAD

**Issue by michael-schramm** [Leantime/leantime#909] opened 2022-08-23 13:43 UTC
**Describe the bug**
All the tasks with status "Done" are still visible in the calendar and being shown with status "Due To-Do"

**To Reproduce**
1. Go to a task on the calendar.
2. Check change the status to "Done"
3. Click on Calendar.
4. Check the displayed status of that "done" task in the Calendar.
5. You will see it is still shown as "Due To-Do" in the Calendar.

**Expected behavior**
The task with the "done" status should not be shown in the calendar and/or should show the actual status.
**Leantime Version**
2.2.5
**Server**
Apache

**PHP / MySQL Version**
PHP 8.1

**Comment by ashelman-ec** [comment] 2022-08-25 12:54
This is a duplicate of #839 (with a different suggestion for Expected Behavior).

**Closed** 2022-10-14 02:41 UTC
Labels: bug, Fixed and Staged
