### ISSUE TITLE
[FEATURE] Tasks status changes could per project and not a general setting

### ISSUE THREAD

**Issue by archlinux-fan** [Leantime/leantime#560] opened 2022-01-09 18:45 UTC
I would like to use different tasks statuses for different project but that is not possible currently. If you make a change on 1 project it affects all other projects.

I use Leantime for other things and not just web development.

**Comment by indrisepos** [comment] 2022-02-08 23:30
How can statuses be set globally? My Leantime version is 2.1.8

**Comment by marcelfolaron** [comment] 2022-02-09 00:30
That seems to be a bug actually. Statuses are (or should be) stored on a project per project level. Let me check what is going on there.

**Comment by marcelfolaron** [comment] 2022-04-13 00:32
Dupe of #508

**Closed by marcelfolaron** 2022-04-13 00:32 UTC
Labels: bug
