### ISSUE TITLE
User editing/changing password gets error on save: Form token incorrect, please try again

### ISSUE THREAD

**Issue by amurad** [Leantime/leantime#311] opened 2020-07-30 03:04 UTC
A user is unable to edit his own profile or change password. When saving any changes get this error:

![image](https://user-images.githubusercontent.com/2021240/88875411-d259b880-d1e6-11ea-83eb-2434c7ce464c.png)

This happens for all users created.

But admin user (created during installation) has no issues and can save his own profile edits.

**Comment by amurad** [comment] 2020-07-30 03:17
OK, so I don't know if it is by design (it should not be), it looks like if a user is not assigned to any project on creation then the user cannot edit own profile and gets that error on save.

If the user is assigned to a project then no issues. I was simply creating some users for testing and not selecting any project when creating the user.

**Comment by marcelfolaron** [comment] 2020-08-14 23:15
Oh interesting problem. That is not by design. I'll check that use case

**Comment by karman1102** [comment] 2020-09-14 04:47
Hi @marcelfolaron, is there a workaround for this issue right now? Is there any way I can hepl you solve this?

**Comment by marcelfolaron** [comment] 2022-04-21 12:53
Fixed in 2.1.9

**Closed by marcelfolaron** 2022-04-21 12:53 UTC
Labels: bug

**Comment by vmfventura** [comment] 2022-06-06 21:30
I have installed 2.1.9 and still this error.
Any work around?

**Comment by tstanciu** [comment] 2023-01-02 23:22
The problem still happens in 2.3.3
![image](https://user-images.githubusercontent.com/63559907/210284435-656235e0-9056-4b08-9d98-459b1cad80e2.png)
I am connected in the application with the admin user and I am trying to edit another user. Editing does not work and this error appears.
