### ISSUE TITLE
[BUG] Can't delete project

### ISSUE THREAD

**Issue by lamping7** [Leantime/leantime#251] opened 2020-05-05 22:14 UTC
**Describe the bug**
Error: Can't delete project. There are still to-dos in this project. Please delete all to-dos first

**To Reproduce**
1. Click "Project settings"
2. Click "Delete"

**Expected behavior**
It should delete the project.

**Leantime Version**
2.1.0

**Comment by marcelfolaron** [comment] 2020-05-06 02:18
Right now this is actually a feature and working as intended, but I see that one should be able to delete a project with tasks. (Maybe just an extra confirmation)

**Comment by lamping7** [comment] 2020-05-06 02:23
Well, I deleted all the tasks and made sure everything else was gone and it still wouldn't let me.  I'm talking about the premade leantime onboarding project. I'm not sure what else to try. Is there a list of what is required to delete a project?

**Comment by marcelfolaron** [comment] 2020-05-06 02:51
Oh, I see. Sorry about that if you deleted all tasks and still see the
message there is indeed a bug. Let me do some digging.

**Comment by Marcquito** [comment] 2020-05-07 02:38
I just want to mention that I also have this same issue with a project when trying to delete. Checked multiple times and can confirm that no todo items are left in the project. Definitely a head scratcher!

**Comment by lamping7** [comment] 2020-05-07 14:43
I was able to delete one of them. I think there are more things being counted as "To-Do"s. I had to delete all boards and milestones. I'm not sure if deleted ones doesn't update the count associated with a milestone. I'm not sure.

I have another project with nothing left in it except for a retrospective that I can't delete. It won't let me delete the retrospective. If I add another retrospective, then I can delete the previous one, but then the same things happens with this newly created one. It states "Research board successfully deleted," which is also weird, because this isn't "Research board," it's a "Retrospective."

More issues with the last project discussed -- which may provide insight:
 - The "Reports" tab shows 8 "Open To-Dos"
 - The "Project Dashboard" is empty
 - "Administration" --> "All Projects" shows that that project has 4 "Number of To-Dos"

**Comment by marcelfolaron** [comment] 2020-05-07 15:37
Thanks all.
I think I found the issue. The to-do counter counts everything in the
zp_tickets table which includes Milestones and Subtasks. Now in addition to
that issue it is possible to get into a state where a main task is deleted
but the subtasks remain at which point a project deletion is not possible.
Here is what I'll do

1. Allow project deletion no matter what
2. Ensure all related items (todos, ideas etc) will get deleted at the same.
3. Double check the to-do counters across the system to ensure we show the
correct number.

Anything else you can think of?

I should have a fix ready by the weekend.

**Comment by lamping7** [comment] 2020-05-07 16:26
The situation you explained is likely what happened. Obviously my workflow wasn't normal here. I was demoing the software and learning it, while evaluating it for my team. We're now going to try to use it seriously. 

Awesome. Just a note -- The UI is a little weird here. You click the red trash can and word delete. You then get a taken to a landing page to confirm deletion. The weird part is that this error is shown before you click the yes-really-delete-it button and the page let's you still click it. 

Another thing to consider is archiving a project. The project could be archived (read-only) and maybe restored if your a Administrator or or Company Manager. Archiving it could remove it from view of other, less important roles. This is obviously more of a feature request, but a valid one.

One more completely unrelated note -- I can't access the administration items without there existing or being assigned to one project. I'm limited to only seeing the "new project" page. I'd be helpful to be able to setup users and clients and other administrative stuff before the project. Think: Maybe the person seating up leantime is not a project manager or has little affiliation with the business.

Any thoughts about the "Retrospective" issue in my last comment?

**Comment by marcelfolaron** [comment] 2020-05-07 16:56
Hi,

*Awesome. Just a note -- The UI is a little weird here. You click the red
trash can and word delete. You then get a taken to a landing page to
confirm deletion. The weird part is that this error is shown before you
click the yes-really-delete-it button and the page let's you still click
it.*

That should not be a problem moving forward if we always allow deleting
projects. It will just be a notice at the top


*Another thing to consider is archiving a project. The project could be
archived (read-only) and maybe restored if your a Administrator or or
Company Manager. Archiving it could remove it from view of other, less
important roles. This is obviously more of a feature request, but a valid
one.*

This is already possible (partly). The project settings screen has a status
field. If you change that to "Closed" it will disappear from most lists
(you can still make changes though, so that part would be a new feature)


*One more completely unrelated note -- I can't access the administration
items without there existing or being assigned to one project. I'm limited
to only seeing the "new project" page. I'd be helpful to be able to setup
users and clients and other administrative stuff before the project. Think:
Maybe the person seating up leantime is not a project manager or has little
affiliation with the business.*

I'll have to check that workflow again. You are right admins should be able
to do everything they need without being assigned to a project.

*Any thoughts about the "Retrospective" issue in my last comment?*

Will investigate and get back to you

**Comment by rpacheco2019** [comment] 2020-05-11 11:59
Hello! For me, deleting the milestone was necessary to delete the whole project. I just have 1 retrospective but i was able to delete it. I'll be here to check your update , thanks!

**Closed** 2020-05-14 03:19 UTC
Labels: bug
