### ISSUE TITLE
Problem with polish fonts.

### ISSUE THREAD

**Issue by terminusik** [Leantime/leantime#1673] opened 2023-06-05 10:30 UTC
![obraz](https://github.com/Leantime/leantime/assets/12064993/1ea2526b-6806-4cdf-b229-6db1016881a8)
How to resolve problems with polish fonts?? I can change fonts, but it not works.

**Comment by mobilex1122** [comment] 2023-06-05 13:33
I have the same problem with Czech characters. I think that this due to a lack of unicode support for this font. It would be great if you could change.
![image](https://github.com/Leantime/leantime/assets/60009551/2a80bf94-1df0-470d-a52a-f9ecc6f9a2d4)

**Comment by phavel** [comment] 2023-06-09 21:13
I have the same problem too. I think, it is duplicate of #422, but unresolved.

**Closed** 2023-06-12 17:10 UTC
Labels: Completed

**Comment by phavel** [comment] 2023-06-12 21:04
Thanks for the repair!
