### ISSUE TITLE
[ POSSIBLE BUG] Side-menu shows empty in v2.3.5 until project is added

### ISSUE THREAD

**Issue by sunrez** [Leantime/leantime#1291] opened 2023-01-16 01:57 UTC
**Describe the bug**
With a new 2.3.5, the menu on the left is completely empty until a project is added then all the 'normal entries' appear.

**Expected behavior**
I don't know if this is expected or not, but it seems different compared to 2.3.4 ; possible something with my composer / npm set up wasn't correct since previously I was using a release vs. a git clone / building the assets.

**Leantime Version**
2.3.5

**Server**
nginx with the configuration packaged with leantime

**PHP / MySQL Version**
PHP-8.2 , mariadb-server 10.5

**Comment by marcelfolaron** [comment] 2023-01-21 19:57
That is by design. If a user is not assigned to a project there is no project releated menu available.

**Closed by marcelfolaron** 2023-01-21 19:57 UTC
Labels: bug
